name: CI/CD Pipeline - Flag Explorer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Backend
      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Install jest-junit for test reporting
        run: cd backend && npm install --save-dev jest-junit

      - name: Run backend tests
        run: cd backend && npm test

      # Frontend
      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Run frontend tests
        run: cd frontend && npm test

      - name: Build frontend
        run: cd frontend && npm run build

      # Package backend
      - name: Package backend
        run: zip -r backend.zip backend

      # Package frontend
      - name: Package frontend
        run: zip -r frontend.zip frontend/build

      # Upload backend artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip

      # Upload frontend artifact
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: frontend.zip
